# Step 1 : Import Required Libraries

In [4]:
import pandas as pd
import numpy as np

# Step 2 : Load Dataset

In [6]:
df = pd.read_csv("Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

# Step 3 : Check data set Information

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [8]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [9]:
df.size

900

In [10]:
df.shape

(150, 6)

# Step 4 : Summary Statistics

In [11]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

# Step 5 : Group by categorical Values

In [12]:
grouped_stats = df.groupby('Species').agg(['mean', 'median', 'min', 'max', 'std'])
grouped_stats

                    Id                            SepalLengthCm              \
                  mean median  min  max       std          mean median  min
Species
Iris-setosa       25.5   25.5    1   50  14.57738         5.006    5.0  4.3
Iris-versicolor   75.5   75.5   51  100  14.57738         5.936    5.9  4.9
Iris-virginica   125.5  125.5  101  150  14.57738         6.588    6.5  4.9

                                ... PetalLengthCm                             \
                 max       std  ...          mean median  min  max       std
Species                         ...
Iris-setosa      5.8  0.352490  ...         1.464   1.50  1.0  1.9  0.173511
Iris-versicolor  7.0  0.516171  ...         4.260   4.35  3.0  5.1  0.469911
Iris-virginica   7.9  0.635880  ...         5.552   5.55  4.5  6.9  0.551895

                PetalWidthCm
                        mean median  min  max       std
Species
Iris-setosa            0.244    0.2  0.1  0.6  0.107210
Iris-versicolor        1.326    1.3  1.0  1.8  0.197753
Iris-virginica         2.026    2.0  1.4  2.5  0.274650

[3 rows x 25 columns]

# Step 6 :Create List for each category

In [14]:
setosa_list = df[df['Species'] == "Iris-setosa"]['PetalLengthCm'].tolist()
versicolor_list = df[df['Species'] == "Iris-versicolor"]['PetalLengthCm'].tolist()
virginica_list = df[df['Species'] == "Iris-virginica"]['PetalLengthCm'].tolist()

print("Setosa:", setosa_list[:5])
print("Versicolor:", versicolor_list[:5])
print("Virginica:", virginica_list[:5])

Setosa: [1.4, 1.4, 1.3, 1.5, 1.4]
Versicolor: [4.7, 4.5, 4.9, 4.0, 4.6]
Virginica: [6.0, 5.1, 5.9, 5.6, 5.8]

# Step 7 : Statistical details for each species

In [15]:
setosa = df[df['Species'] == "Iris-setosa"]
versicolor = df[df['Species'] == "Iris-versicolor"]
virginica = df[df['Species'] == "Iris-virginica"]

print("Setosa Statistics")
print(setosa.describe())

print("\nVersicolor Statistics")
print(versicolor.describe())

print("\nVirginica Statistics")
print(virginica.describe())

Setosa Statistics
             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

Versicolor Statistics
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

Virginica Statistics
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000

# Step 8 : Percentile calculation

In [16]:
print("25th Percentile")
print(df.groupby('Species').quantile(0.25))

print("\n50th Percentile")
print(df.groupby('Species').quantile(0.50))

print("\n75th Percentile")
print(df.groupby('Species').quantile(0.75))

25th Percentile
                     Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa       13.25          4.800         3.125            1.4
Iris-versicolor   63.25          5.600         2.525            4.0
Iris-virginica   113.25          6.225         2.800            5.1

                 PetalWidthCm
Species
Iris-setosa               0.2
Iris-versicolor           1.2
Iris-virginica            1.8

50th Percentile
                    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa       25.5            5.0           3.4           1.50
Iris-versicolor   75.5            5.9           2.8           4.35
Iris-virginica   125.5            6.5           3.0           5.55

                 PetalWidthCm
Species
Iris-setosa               0.2
Iris-versicolor           1.3
Iris-virginica            2.0

75th Percentile
                     Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa       37.75            5.2         3.675          1.575
Iris-versicolor   87.75            6.3         3.000          4.600
Iris-virginica   137.75            6.9         3.175          5.875

                 PetalWidthCm
Species
Iris-setosa               0.3
Iris-versicolor           1.5
Iris-virginica            2.3